FROM php:8.2-fpm-alpine

# Installer les dépendances nécessaires pour Laravel & MySQL
RUN apk add --no-cache \
    zip unzip curl libpng-dev libonig-dev libxml2-dev

RUN docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd

# Installer Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /var/www

# Copier les fichiers du projet
COPY . .

# Installer les packages PHP
RUN composer install --no-dev --optimize-autoloader

# Configurer les permissions des dossiers de stockage
RUN chown -R www-data:www-data /var/www/storage /var/www/bootstrap/cache

EXPOSE 9000
CMD ["php-fpm"]